#!/bin/sh

# Copyright (C) 2015 William Wennerström
#
# This program is free software:
# You can redistribute it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, version. This program is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.

FILES=''
ADDRESS='https://nup.pw'

print_help () {
  echo -e '\nAuthor: William Wennerström (willeponken) <william@willeponken.me>'
  echo -e 'License: GPL-3.0 - see source file\n'
  echo -e 'Usage: nupup [-a http(s)://address] [-h] file ..\n'
  echo -e '\t-a {http(s)://address}\tUpload address.'
  echo -e '\t-h\t\t\tUse the Hyperboria address (h.nup.pw).'
  echo -e '\tfile ..\t\t\tA list of file names.\n'
}

while getopts 'ha:' opt; do
  case $opt in
    a)
      ADDRESS=$OPTARG
      ;;
    h)
      ADDRESS='http://h.nup.pw'
      ;;
    \?)
      echo 'Invalid option: -$OPTARG' >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

[ -z $1 ] && print_help && exit 1

for file in $@
do
  FILES=$FILES' -F file[]=@'$file;
done

curl -# $FILES $ADDRESS | grep li | tr -d " "| tr \<,\> "$" | cut -d"$" -f 5,9 --output-delimiter=": "
